name: upkeep

on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  plexamp:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Checkout nixpkgs-upkeep
        uses: actions/checkout@v2
        with:
          path: nixpkgs-upkeep

      - name: Checkout nixpkgs
        uses: actions/checkout@v2
        with:
          repository: NixOS/nixpkgs
          path: nixpkgs
          token: ${{ secrets.GH_TOKEN }}

      # Plexamp is unfree, so we need to ok that in our Nix config.
      - run: |
          mkdir -p ~/.config/nixpkgs/
          echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix

      - name: Check current package version
        working-directory: ./nixpkgs
        run: |
          PACKAGE="plexamp"
          CURRENT_VERSION="$(nix eval --raw -f . $PACKAGE.version)"
          echo "PACKAGE=$PACKAGE" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Run custom update-script
        run: |
          ./nixpkgs/pkgs/applications/audio/plexamp/update-plexamp.sh

      - working-directory: ./nixpkgs
        run: git diff

      - name: Create PR
        working-directory: ./nixpkgs
        run: |
          GH_TOKEN=$GH_TOKEN \
            PACKAGE=$PACKAGE \
            CURRENT_VERSION=$CURRENT_VERSION \
            TESTED_OTHER_LINUX="false" \
            GITHUB_WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            ./../nixpkgs-upkeep/create-pr.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
